apiVersion: apps/v1 
kind: Deployment
metadata:
  name: staging-deployment
spec:
  selector:
    matchLabels:
      app: staging
  replicas: 1 
  template:
    metadata:
      labels:
        app: staging
    spec:
      containers:
      - name: staging
        image: {{ .Values.image }}:{{ .Values.tag }}
        ports:
        - containerPort: 3000
        env:
        - name: TAG
          value: {{ .Values.tag }}